apiVersion: v1
kind: Service
metadata:
  name: time-dashboard-service
spec:
  type: NodePort
  selector:
    app: time-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007